server:
  port: 8080                           # 서버 포트
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dive            # H2 인메모리 DB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: hikari-mysql
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jwt:
    secret: "ssKZNADWYanEpMggbTIsawoOvT31Vx6rII+MYJPipYZmFI4MiYhJLSa/6MeG7fnymqX5b4M5XTdnNsile3mAyg==" # JWT 서명키(최소 32바이트 권장)
  security:
    oauth2:
      redirect:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: 17a790294a02e3feca27d91721d05bbe
            client-secret: 8116Svp16uiqDmZa4WOLll7dCL8NHj2N
            scope: account_email, profile_nickname
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri:  https://kauth.kakao.com/oauth/authorize
            token-uri:          https://kauth.kakao.com/oauth/token
            user-info-uri:      https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


app:
  jwt:
    access-exp-minutes: 30
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.DIVE2025.domain
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 5

logging:
  level:
    com.example.DIVE2025: DEBUG
    org.mybatis: DEBUG